### ISSUE TITLE
docs.python.org pages have stale version pickers -> make cache expire faster

### ISSUE THREAD

**Issue by ned-deily** [python/psf-salt#63] opened 2015-09-16 17:28 UTC
The Sphinx-generated Python doc pages on docs.python.orgs each have an embedded JS version picker that is included in the daily docs rebuild.  The version numbers are updated with new releases.  But it seems that the CDN cache max age is currently set to 604800 secs (a week).  It would be better if the cache expired more frequently, say daily, so that the docs were more up-to-date.  There's a lot of confusion at the moment due to the Python 3.5.0 release doc updates (for example, http://bugs.python.org/issue25113).

On #python-infra, @dstufft suggested changing "Surrogate-control: max-age=604800" here:

https://github.com/python/psf-salt/blob/master/salt/docs/config/nginx.docs-backend.conf#L15

and possibly also setting stale-while-revalidate
"like Surrogate-Control: max-age=NNN, stale-while-revalidate=NNN
that'll cause Fastly to serve a "stale" (e.g. older than the max-age document) to someone while it goes in the background and refetches the latest version of that page
so people still get almost all docs served from Fastly's cache, but fastly's cache stays more current"

**Comment by gutworth** [comment] 2015-09-26 06:14
The documentation is invalidated as needed when it is automatically rebuilt. Unfortunately, the automatic rebuilding rather frequently breaks due to manual changes on the server. I've now repaired it again.

**Comment by brainwane** [comment] 2020-05-28 00:17
@ewdurbin can we take a look at this, maybe tomorrow, to check reproducibility and see whether it needs fixing? This came up in the context of closing out the Python 2 sunsetting communications tasks.

**Comment by ned-deily** [comment] 2020-05-28 00:21
You should involve @JulienPalard in this as he is the cpython documentation expert responsible for maintaining the docsbuild system.

**Comment by ned-deily** [comment] 2020-05-28 00:29
In theory, each rebuild of the docs should invalidate the cache for each changed page but there may be an issue with some of the JS files pulled into a page like the version picker.  There are also issues of browsers just not updating their caches unexpectedly; I've seen this with Safari, for example, where I purged the version picker cached on the CDN, verified that the version picker file was in fact updated by downloading via curl, yet repeated refreshes in the browser continued to use the out-of-date version picker until the browser was restarted.

**Comment by JulienPalard** [comment] 2020-05-28 07:54
Yes, rebuilds are [automatically invalidating cache](https://github.com/python/docsbuild-scripts/blob/e71030cf1c96193c162fd6c9ad45b362bb1e0848/build_docs.py#L405), so there is no need to lower the cache retention time. I think this issue can be closed. (I don't have a safari to test though).

**Comment by ewdurbin** [comment] 2020-06-04 16:47
I think the only surefire fix is to add a form of cache busting to the url for switcher.js itself.

It is served with appropriate Last Modified and etag headers, but browsers may helpfully ignore those.

I recommend closing this, and opening an issue on https://github.com/python/docsbuild-scripts to discuss cache-busting for CSS and JS assets.

**Closed** 2020-06-04 17:37 UTC
